use std::collections::BTreeSet;
use std::sync::OnceLock;

use codex::Def;

use crate::scheme;
use crate::symbol::Symbol;

/// The embedded `unicode-math-table.tex` (vendored from the `unicode-math`
/// package; see `data/README.md`).
const TABLE: &str = include_str!("../data/unicode-math-table.tex");

/// Vendored, normalized table for the `latex` scheme, generated by
/// `scripts/update-latex-symbols.py` (see `data/README.md` for source/licence).
const LATEX_TSV: &str = include_str!("../data/latex-symbols.tsv");

/// Starter set of ASCII digraph aliases: `(name, character, description)`.
///
/// These map punctuation sequences to the non-ASCII characters they evoke. It is
/// deliberately small and uncontroversial.
const ASCII_ALIASES: &[(&str, char, &str)] = &[
    ("->", '→', "rightwards arrow"),
    ("<-", '←', "leftwards arrow"),
    ("<->", '↔', "left right arrow"),
    ("=>", '⇒', "rightwards double arrow"),
    ("<=", '≤', "less-than or equal to"),
    (">=", '≥', "greater-than or equal to"),
    ("!=", '≠', "not equal to"),
    ("|->", '↦', "maps to"),
    ("+-", '±', "plus-minus sign"),
    ("-+", '∓', "minus-plus sign"),
    ("<=>", '⇔', "left right double arrow"),
    ("...", '…', "horizontal ellipsis"),
];

/// All symbols across every built-in scheme.
///
/// Parsed once, on first access, and cached for the lifetime of the program:
/// `unicode-math` (in table order), the ASCII aliases, Typst's `sym` names, then
/// the `latex` table. Each [`Symbol`] is tagged with its [`scheme`](crate::scheme).
/// (The `unicode` scheme is dynamic and has no entries here.)
pub fn symbols() -> &'static [Symbol] {
    static SYMBOLS: OnceLock<Vec<Symbol>> = OnceLock::new();
    SYMBOLS
        .get_or_init(|| {
            let mut all: Vec<Symbol> = TABLE.lines().filter_map(parse_line).collect();
            all.extend(ASCII_ALIASES.iter().map(|&(name, ch, description)| Symbol {
                scheme: scheme::ASCII,
                name: name.to_string(),
                value: ch.to_string(),
                class: None,
                description,
            }));
            collect_typst(&mut all);
            parse_tsv(scheme::LATEX, LATEX_TSV, &mut all);
            all
        })
        .as_slice()
}

/// Completion candidates within a single scheme for the given `query` — the
/// already-extracted name fragment, without any trigger prefix. Matches names in
/// `scheme_id` that start with `query`, preserving insertion order.
///
/// When `include_ascii` is `false`, symbols whose value is a single ASCII
/// character are skipped.
pub fn complete_in<'a>(
    scheme_id: &'a str,
    query: &'a str,
    include_ascii: bool,
) -> impl Iterator<Item = &'static Symbol> + 'a {
    symbols().iter().filter(move |s| {
        s.scheme == scheme_id && (include_ascii || !s.is_ascii()) && s.name.starts_with(query)
    })
}

/// The set of characters appearing in the names of `scheme_id`.
///
/// For operator-triggered schemes this is the alphabet an editor integration uses
/// to find the token under the cursor (e.g. `=`, `>`, `-`).
pub fn name_chars(scheme_id: &str) -> BTreeSet<char> {
    symbols()
        .iter()
        .filter(|s| s.scheme == scheme_id)
        .flat_map(|s| s.name.chars())
        .collect()
}

/// Parse a single `\UnicodeMathSymbol{"HEX}{\macro}{\class}{description}%` line
/// into a `unicode-math` [`Symbol`]. Returns `None` for comments, blank lines,
/// and anything that does not match the expected shape.
fn parse_line(line: &'static str) -> Option<Symbol> {
    let rest = line.strip_prefix("\\UnicodeMathSymbol{\"")?;
    let (hex, rest) = rest.split_once('}')?;
    let ch = char::from_u32(u32::from_str_radix(hex.trim(), 16).ok()?)?;

    // Macro and class fields carry a leading backslash and trailing padding.
    let (name, rest) = field(rest)?;
    let name = name.strip_prefix('\\')?.trim_end();

    let (class, rest) = field(rest)?;
    let class = class.strip_prefix('\\')?.trim_end();

    let (description, _) = field(rest)?;

    Some(Symbol {
        scheme: scheme::UNICODE_MATH,
        name: name.to_string(),
        value: ch.to_string(),
        class: Some(class),
        description,
    })
}

/// Pull the next `{...}` group off the front of `s`, returning its inner text and
/// the remainder after the closing brace.
fn field(s: &str) -> Option<(&str, &str)> {
    s.strip_prefix('{')?.split_once('}')
}

/// Parse a vendored TSV table — `name<TAB>codepoint(hex)[ ...]<TAB>description`,
/// description optional — into symbols for `scheme_id`. Lines starting with `#`
/// and malformed lines are skipped. See `data/*.tsv` and `data/README.md`.
fn parse_tsv(scheme_id: &'static str, data: &'static str, out: &mut Vec<Symbol>) {
    for line in data.lines() {
        let line = line.trim_end();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut cols = line.splitn(3, '\t');
        let (Some(name), Some(codes)) = (cols.next(), cols.next()) else {
            continue;
        };
        let description = cols.next().unwrap_or("");

        let mut value = String::new();
        let valid = codes.split(' ').all(|hex| {
            match u32::from_str_radix(hex, 16).ok().and_then(char::from_u32) {
                Some(c) => {
                    value.push(c);
                    true
                }
                None => false,
            }
        });

        if valid && !name.is_empty() && !value.is_empty() {
            out.push(Symbol {
                scheme: scheme_id,
                name: name.to_string(),
                value,
                class: None,
                description,
            });
        }
    }
}

/// Walk Typst's `sym` module (from the `codex` crate) and push one [`Symbol`] per
/// non-deprecated variant. Names are the dotted module/symbol/modifier paths,
/// e.g. `arrow.r.double`.
fn collect_typst(out: &mut Vec<Symbol>) {
    fn walk(module: codex::Module, path: &str, out: &mut Vec<Symbol>) {
        for (name, binding) in module.iter() {
            if binding.deprecation.is_some() {
                continue;
            }
            let base = if path.is_empty() {
                name.to_string()
            } else {
                format!("{path}.{name}")
            };
            match binding.def {
                Def::Module(sub) => walk(sub, &base, out),
                Def::Symbol(symbol) => {
                    for (modifiers, value, deprecation) in symbol.variants() {
                        if deprecation.is_some() {
                            continue;
                        }
                        let mods = modifiers.as_str();
                        let full = if mods.is_empty() {
                            base.clone()
                        } else {
                            format!("{base}.{mods}")
                        };
                        out.push(Symbol {
                            scheme: scheme::TYPST,
                            name: full,
                            value: value.to_string(),
                            class: None,
                            description: "",
                        });
                    }
                }
            }
        }
    }

    if let Some(binding) = codex::ROOT.get("sym") {
        if let Def::Module(module) = binding.def {
            walk(module, "", out);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn find(scheme_id: &str, name: &str) -> &'static Symbol {
        symbols()
            .iter()
            .find(|s| s.scheme == scheme_id && s.name == name)
            .unwrap_or_else(|| panic!("expected symbol `{scheme_id}:{name}` to exist"))
    }

    fn count(scheme_id: &str) -> usize {
        symbols().iter().filter(|s| s.scheme == scheme_id).count()
    }

    #[test]
    fn parses_every_macro_line() {
        let macro_lines = TABLE
            .lines()
            .filter(|l| l.starts_with("\\UnicodeMathSymbol"))
            .count();
        assert_eq!(count(scheme::UNICODE_MATH), macro_lines);
    }

    #[test]
    fn unicode_math_snapshot_count() {
        // Tracks the vendored table; bump intentionally on update.
        assert_eq!(count(scheme::UNICODE_MATH), 2448);
    }

    #[test]
    fn known_unicode_math_symbols() {
        let leq = find(scheme::UNICODE_MATH, "leq");
        assert_eq!(leq.value, "≤");
        assert_eq!(leq.codepoint(), Some(0x2264));
        assert_eq!(leq.usv().as_deref(), Some("U+2264"));
        assert_eq!(leq.class, Some("mathrel"));

        assert_eq!(find(scheme::UNICODE_MATH, "lparen").value, "(");
        assert_eq!(find(scheme::UNICODE_MATH, "BbbR").value, "ℝ");
        assert_eq!(find(scheme::UNICODE_MATH, "mupalpha").value, "α");
    }

    #[test]
    fn ascii_aliases_present() {
        let arrow = find(scheme::ASCII, "=>");
        assert_eq!(arrow.value, "⇒");
        assert_eq!(arrow.class, None);
        assert_eq!(find(scheme::ASCII, "->").value, "→");
    }

    #[test]
    fn typst_symbols_present() {
        assert!(count(scheme::TYPST) > 1000);
        assert_eq!(find(scheme::TYPST, "alpha").value, "α");
        assert_eq!(find(scheme::TYPST, "Alpha").value, "Α");
        assert_eq!(find(scheme::TYPST, "arrow.r").value, "→");
        assert_eq!(find(scheme::TYPST, "arrow.r.double").value, "⇒");
        assert_eq!(find(scheme::TYPST, "eq.not").value, "≠");
        assert_eq!(find(scheme::TYPST, "lt.eq").value, "≤");
        assert_eq!(find(scheme::TYPST, "alpha").class, None);
    }

    #[test]
    fn typst_has_variation_selector_values() {
        // arrow.l.r is "↔" + a text-presentation variation selector (2 chars).
        let lr = find(scheme::TYPST, "arrow.l.r");
        assert!(lr.value.chars().count() >= 2);
        assert!(lr.single_char().is_none());
        assert!(!lr.is_ascii());
    }

    #[test]
    fn names_and_values_nonempty() {
        assert!(symbols().iter().all(|s| !s.name.is_empty()));
        assert!(symbols().iter().all(|s| !s.value.is_empty()));
        assert!(symbols().iter().all(|s| s.name == s.name.trim()));
    }

    #[test]
    fn complete_in_filters_by_scheme_and_prefix() {
        let names: Vec<_> = complete_in(scheme::UNICODE_MATH, "leq", false)
            .map(|s| s.name.as_str())
            .collect();
        assert!(names.contains(&"leq"));
        assert!(names.iter().all(|n| n.starts_with("leq")));
        assert!(complete_in(scheme::UNICODE_MATH, "leq", false)
            .all(|s| s.scheme == scheme::UNICODE_MATH));

        // Typst dotted prefix matching.
        let typst: Vec<_> = complete_in(scheme::TYPST, "arrow.r", false)
            .map(|s| s.name.as_str())
            .collect();
        assert!(typst.contains(&"arrow.r.double"));
        assert!(typst.iter().all(|n| n.starts_with("arrow.r")));
    }

    #[test]
    fn complete_in_excludes_ascii_targets_by_default() {
        // \lparen -> '(' is an ASCII *target*: hidden by default, shown on request.
        assert!(!complete_in(scheme::UNICODE_MATH, "lparen", false).any(|s| s.name == "lparen"));
        assert!(complete_in(scheme::UNICODE_MATH, "lparen", true).any(|s| s.name == "lparen"));
    }

    #[test]
    fn ascii_name_chars() {
        let chars = name_chars(scheme::ASCII);
        assert!(chars.contains(&'='));
        assert!(chars.contains(&'>'));
        assert!(chars.contains(&'|'));
        assert!(!chars.contains(&'a'));
    }

    #[test]
    fn latex_scheme_present() {
        assert!(count(scheme::LATEX) > 500);
        assert_eq!(find(scheme::LATEX, "alpha").value, "α");
        assert_eq!(find(scheme::LATEX, "leq").value, "≤");
        assert_eq!(find(scheme::LATEX, "le").value, "≤"); // AMS alias
        assert_eq!(find(scheme::LATEX, "subseteq").value, "⊆");
        // latex entries carry a description (the Unicode character name).
        assert!(!find(scheme::LATEX, "alpha").description.is_empty());
    }
}
