#!/usr/bin/env python3
"""Generate crates/unikodo-core/data/latex-symbols.tsv (the `latex` scheme).

Source : https://www.w3.org/Math/characters/unicode.xml
         W3C "XML Entity Definitions for Characters" (David Carlisle et al.)
License: W3C Software and Document License. The derived table is attributed; see
         crates/unikodo-core/data/README.md.

We keep only "clean" single-token commands (\\word, letters only), so familiar
names like \\alpha, \\leq, \\rightarrow, \\subseteq are included while argument
forms such as \\mathbb{R} are skipped (use the unicode-math / typst schemes for
those). Names are taken from the latex/AMS/varlatex/mathlatex fields.
"""
import os
import re
import urllib.request
import xml.etree.ElementTree as ET

URL = "https://www.w3.org/Math/characters/unicode.xml"
DEST = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..", "crates", "unikodo-core", "data", "latex-symbols.tsv",
)
CLEAN = re.compile(r"^\\[A-Za-z]+$")
FIELDS = ["latex", "AMS", "varlatex", "mathlatex"]  # priority order


def main():
    print(f"Fetching {URL}")
    root = ET.fromstring(urllib.request.urlopen(URL).read())
    seen = {}  # name -> (hex, description)
    for ch in root.iter("character"):
        idv = ch.get("id", "")
        if not idv.startswith("U") or "-" in idv:
            continue  # skip non-single-codepoint entries
        try:
            cp = int(idv[1:], 16)
        except ValueError:
            continue
        if cp < 0x20:
            continue
        desc = " ".join((ch.findtext("description") or "").split())
        for field in FIELDS:
            cmd = ch.findtext(field)
            if cmd and CLEAN.match(cmd.strip()):
                seen.setdefault(cmd.strip()[1:], (f"{cp:04X}", desc))

    rows = sorted(seen.items())
    os.makedirs(os.path.dirname(DEST), exist_ok=True)
    with open(DEST, "w", encoding="utf-8") as fh:
        fh.write("# latex scheme: conventional LaTeX + AMS macro names.\n")
        fh.write(f"# Generated by scripts/{os.path.basename(__file__)} from {URL}\n")
        fh.write("# W3C XML Entity Definitions for Characters (W3C license).\n")
        fh.write("# Columns: name<TAB>codepoint(hex)[ ...]<TAB>description\n")
        for name, (hexv, desc) in rows:
            fh.write(f"{name}\t{hexv}\t{desc}\n")
    print(f"Wrote {DEST} ({len(rows)} names)")


if __name__ == "__main__":
    main()
