#!/usr/bin/env python3
"""Generate crates/unikodo-core/data/rocq-symbols.tsv (the `rocq` scheme).

Source : https://raw.githubusercontent.com/rocq-prover/rocq/master/ide/rocqide/default_bindings_src.ml
License: LGPL-2.1-only (rocq-prover/rocq). The derived table is attributed; see
         crates/unikodo-core/data/README.md.

The RocqIDE bindings are OCaml entries of the form
    [ "\\name1"; "\\name2"; ... ], "<char>", [ category; ... ];
We emit one row per alias, with the category name as a description.
"""
import os
import re
import urllib.request

URL = "https://raw.githubusercontent.com/rocq-prover/rocq/master/ide/rocqide/default_bindings_src.ml"
DEST = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..", "crates", "unikodo-core", "data", "rocq-symbols.tsv",
)

ENTRY = re.compile(r'\[([^\]]*)\]\s*,\s*"((?:[^"\\]|\\.)*)"\s*,\s*\[([^\]]*)\]')
QUOTED = re.compile(r'"((?:[^"\\]|\\.)*)"')


def ocaml_unescape(s):
    out, i = [], 0
    while i < len(s):
        c = s[i]
        if c == "\\" and i + 1 < len(s):
            n = s[i + 1]
            if n == "\\":
                out.append("\\"); i += 2
            elif n == '"':
                out.append('"'); i += 2
            elif n == "n":
                out.append("\n"); i += 2
            elif n == "t":
                out.append("\t"); i += 2
            elif n == "u" and i + 2 < len(s) and s[i + 2] == "{":
                j = s.index("}", i)
                out.append(chr(int(s[i + 3:j], 16))); i = j + 1
            elif n == "x":
                out.append(chr(int(s[i + 2:i + 4], 16))); i += 4
            elif n.isdigit():
                out.append(chr(int(s[i + 1:i + 4]))); i += 4
            else:
                out.append(n); i += 2
        else:
            out.append(c); i += 1
    return "".join(out)


def main():
    print(f"Fetching {URL}")
    text = urllib.request.urlopen(URL).read().decode("utf-8")
    categories = dict(re.findall(r'let\s+(\w+)\s*=\s*"([^"]*)"', text))

    rows = {}  # name -> (hex, description)
    for names_blob, value_raw, cats_blob in ENTRY.findall(text):
        value = ocaml_unescape(value_raw)
        if not value or any(ord(c) < 0x20 for c in value):
            continue
        hexv = " ".join(f"{ord(c):04X}" for c in value)
        desc = ""
        for cid in (c.strip() for c in cats_blob.split(";")):
            if cid in categories:
                desc = categories[cid]
                break
        for raw_name in QUOTED.findall(names_blob):
            name = ocaml_unescape(raw_name).lstrip("\\").strip()
            if name:
                rows.setdefault(name, (hexv, desc))

    os.makedirs(os.path.dirname(DEST), exist_ok=True)
    with open(DEST, "w", encoding="utf-8") as fh:
        fh.write("# rocq scheme: RocqIDE default unicode bindings (latex-style).\n")
        fh.write(f"# Generated by scripts/{os.path.basename(__file__)} from {URL}\n")
        fh.write("# rocq-prover/rocq (LGPL-2.1-only).\n")
        fh.write("# Columns: name<TAB>codepoint(hex)[ ...]<TAB>description\n")
        for name, (hexv, desc) in sorted(rows.items()):
            fh.write(f"{name}\t{hexv}\t{desc}\n")
    print(f"Wrote {DEST} ({len(rows)} names)")


if __name__ == "__main__":
    main()
