#!/usr/bin/env python3
"""Generate crates/unikodo-core/data/lean-symbols.tsv (the `lean` scheme).

Source : https://raw.githubusercontent.com/leanprover/vscode-lean4/master/lean4-unicode-input/src/abbreviations.json
License: Apache-2.0 (leanprover/vscode-lean4). The derived table is attributed;
         see crates/unikodo-core/data/README.md.

Snippet-style abbreviations (values containing a `$` placeholder such as
`$CURSOR`/`$1`) are intentionally skipped for now.
"""
import json
import os
import urllib.request

URL = "https://raw.githubusercontent.com/leanprover/vscode-lean4/master/lean4-unicode-input/src/abbreviations.json"
DEST = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..", "crates", "unikodo-core", "data", "lean-symbols.tsv",
)


def main():
    print(f"Fetching {URL}")
    data = json.loads(urllib.request.urlopen(URL).read())
    rows = {}
    skipped = 0
    for name, value in data.items():
        name = name.strip()
        if not name or not value:
            continue
        if "$" in value:  # snippet placeholder — skipped for now
            skipped += 1
            continue
        rows[name] = " ".join(f"{ord(c):04X}" for c in value)

    os.makedirs(os.path.dirname(DEST), exist_ok=True)
    with open(DEST, "w", encoding="utf-8") as fh:
        fh.write("# lean scheme: Lean 4 unicode-input abbreviations.\n")
        fh.write(f"# Generated by scripts/{os.path.basename(__file__)} from {URL}\n")
        fh.write("# leanprover/vscode-lean4 (Apache-2.0). Snippet abbreviations skipped.\n")
        fh.write("# Columns: name<TAB>codepoint(hex)[ ...]\n")
        for name, hexv in sorted(rows.items()):
            fh.write(f"{name}\t{hexv}\n")
    print(f"Wrote {DEST} ({len(rows)} names, {skipped} snippet entries skipped)")


if __name__ == "__main__":
    main()
